name: Deploy Kobweb Site

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Export Site
        run: ./gradlew :site:kobwebExport -PkobwebReuseServer=false

      - name: Add .nojekyll and 404.html
        run: |
          touch site/.kobweb/site/.nojekyll
          if [ -d site/.kobweb/site/pages ]; then
            cp -r site/.kobweb/site/pages/* site/.kobweb/site/
          fi
          if [ -f site/.kobweb/site/index.html ]; then
            cp site/.kobweb/site/index.html site/.kobweb/site/404.html
          fi

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/.kobweb/site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
